ui/console/bower.json
ui/console/index.html

Fixes fetching templates from $templateCache which may cause issues if they are not there yet.

HAWKULAR-25: Add 'hawtio-template-cache' as bower dependency

---

modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
modules/pinger/src/test/java/org/hawkular/component/pinger/test/PingerTest.java

Small refactoring to start a ping on destination add.
This has the benefit that a UI user may enter the URL and then switch to the graphs and with some luck already see some data.

When a destination is added, immediately ping it, so first result is in quicker

---

ui/console/src/main/scripts/gulpfile.js
ui/console/src/main/scripts/package.json

* Gulp-clean is deprecated, using del is suggested.
* Non-private packages should have several properties in package.json like git-repo, etc.

Got rid of node.js warnings

---

ui/console/src/main/scripts/bower.json

After merging this, user will be redirected to 
http://localhost:8080/metrics/addUrl
after accessing http://localhost:8080/
We should inspect the bower version in ui-components and update those, so we don't have to use resolutions in our bower.json.

Updated hawtio-core-navigation to recent version

---

kettle/pom.xml
kettle/src/main/resources/bin/standalone.conf
kettle/src/main/resources/standalone/configuration/hawkular-realm.json
kettle/src/main/scripts/distro-assembly.xml
kettle/src/main/scripts/standalone.xsl

This PR integrates Hawkular Accounts backend into Kettle. The change itself should not be invasive, except for the fact that a `standalone.conf` is to be shipped with it. It is required as we need to add a property to the command line specifying which realm Keycloak should import at boot.

Added integration with hawkular accounts

---

ui/console/src/main/scripts/bower.json

to match those from hawkular-ui-console alert changes.

Bower Resolutions are required in ui console 

---

ui/README.adoc
ui/console/pom.xml

Profiles add/changed:
* -Plink: Is using bower link functionality for linking the local hawkular-ui-components bower package.
* -Pcache: Was the `dev` profile before. It's used to persist (not download) node.js related stuff (npm/bower packages). The profile was renamed so it doesn't interfere with the `dev` profile anymore which has much broader functionality (creating user, etc) these days.

Updating maven build profiles

---

pom.xml

We are going to need at least 0.0.6 so leaving it at snapshot version for now as the rest of the deps.
WARNING: 0.0.6-SNAPSHOT doesn't seem to be fully available in the nexus yet.

Update inventory to 0.0.6-SNAPSHOT

---

modules/pinger/pom.xml
modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
modules/pinger/src/main/java/org/hawkular/component/pinger/TraitsPublisher.java

* use JNDI instead of CDI for inventory injection to prevent initialization
errors (kudos to jpkroehling for suggesting that)
* fix resource update when publishing traits
This depends on https://github.com/hawkular/hawkular-inventory/pull/69.
With both the inventory fixes and this PR in, it is possible to add URLs and monitor them successfully. Delete is still broken and will have to be fixed on the inventory side in a separate PR (there's non-trivial amount of work needed to make it work correctly).

Pinger fixes:

---

dist/docker/README.adoc
dist/src/main/resources/wildfly/patches/standalone.xsl

and the fixed one for the server->KC requests.
This is to fix running Hawkular inside Docker, where the IP / port of the docker container is different than localhost:8080.

HAWKULAR-249 Use a relative resource for auth 

---

dist/assembly.xml

Adding hawkular-realm-for-dev.json in the hawkular-dist as optional file makes easy to populate a demo user when using the hawkular-dist from nexus.
If not, a pre-process to get the UUID is needed and makes things more difficult to start using hawkular from a pom.xml

Add template realm as optional

---

dist/src/main/resources/wildfly/patches/standalone.xsl

only put jdoe in config for dev builds. production builds, the agent will be disabled by default and the user is required to enable it and configure it with their own user/pass credentials

HAWKULAR-276 - only put jdoe in config for dev builds.

---

pom.xml

the UI needs to know what display name to show for resources. this moves the agent to 0.0.6 which will add a name property to all resources so the UI can refer to them

move to agent 0.0.6

---

pom.xml

The first step towards having metrics 0.3.4. The tests are expected to fail.

Upgrade metrics to 0.3.4

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-server-list.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerList.ts

Enhancements:
- Fix Last Update position and text in URL list;
- Show information boxes when no app servers are configured;
- Add "Fetching state" to app servers when no state has been retrieved yet;
- Get availability for URL list from Availability endpoint instead of through status code;
- Reduce amount of requested data for showing current response time (1h instead of 24h);
- Use distinct=true param for App Server list availability;

HAWKULAR-303: Fix Last downtime in URL list and other enhancements

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/alerts-setup.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAlerts.ts

I didn't check at all the code and if this typo needs a fix in other components.

HAWKULAR-329: 'miliseconds' spelled wrong

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/alerts-view.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/availability.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/response-time.html
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/less/metrics-main.less

- URLs list: aligned time, replaced remove tooltip
- moved success feedback above the alerts empty box
- availability/response time: placed the tooltip at the top
- response time: aligned legend to the left
- alerts modal: fixed help text (was becoming red)

Design adjustments on the UI

---

ui/console/src/main/scripts/bower.json

Current hawkular-charts has broke this hawkular console bower dependency. This is just to fix this problem.

Fix Hawkular Charting dependencies now that d3 version changed

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts
ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsResponsePage.ts

This PR is required for the console to handle metrics correctly, but there still seem to be a server-side issue in this branch. I've got plenty of these errors in the log:
```
14:14:46,678 ERROR [org.apache.cassandra.service.CassandraDaemon] (ActiveMQ VMTransport: vm://org.hawkular.bus.broker.vrockai-laptop#7-2) Exception in thread Thread[ActiveMQ VMTransport: vm://org.hawkular.bus.broker.vrockai-laptop#7-2,5,ServerService ThreadGroup]: org.apache.activemq.broker.BrokerStoppedException: Broker BrokerService[org.hawkular.bus.broker.vrockai-laptop] is being stopped
at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:153)
at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
at …
```

HAWKULAR-379: Fixed parameter name in rest call

---

dist/src/main/resources/wildfly/patches/standalone.xsl

Although using embedded cassandra should also enable the waitForService option, when embedded C* goes away we will still want this option enable. With this option deployments can add dependencies on api-jaxrs to ensure metrics is initialized (and possibly install the schema) before themselves getting deployed.

set metrics waitForStart true by default in standalone.xml

---

pom.xml

**This is different from https://github.com/hawkular/hawkular/tree/dev/inventory-0.1.0.Alpha3**.
On top of the tested `0.1.0.Alpha2` which is currently in master, `0.1.0.Alpha3` contains only a fix for bug https://issues.jboss.org/browse/HWKINVENT-54 and therefore gets rid of the ugly error where agent is not able to fully sync its resource types with the server.
No other changes are present and most notably, no UI changes are necessary for this to work in Hawkular 1.0.0.Alpha2.

Update dist to use Inventory 0.1.0.Alpha3.

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAvailabilityPage.ts

Currently the metrics endpoint is returning data as if we had been monitoring for the whole specified time range, which may not be the case. This should be fixed in metrics.

HAWKULAR-347 : Fix downtime information in URL availability detail tab

---

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts

The fix reverses the results array, but metrics should return it in reverse order (more recent first)

HAWKULAR-366 : Fix availability info for URL list

---

console/src/main/scripts/plugins/metrics/html/availability.html

Because "2 hours" is not accurate when it's actually "2 hours 59 minutes"

HAWKULAR-415 : Show secondary unit in humanized downtime information

---

README.adoc

Travis shows red badge on the GitHub readme even if some build for other branch fails, in my opinion and in ideal world the badge should show the status of the branch I am looking at in the GitHub, unfortunatelly it's not currently possible (https://github.com/travis-ci/travis-ci/issues/1892). So at least let's make the icon mean the status of the last build for master branch, and not 'status of the last build of any branch'

Travis badge with status only of builds of master branch

---

console/src/main/scripts/plugins/metrics/ts/alertsManager.ts

In TypeScript it's not possible to override/shadow the eval function in the strict mode

Fixing the gulp build (Invalid use of 'eval')

---

.travis.yml

same thing as inventory has (http://git.io/vYT7m, https://travis-ci.org/hawkular/hawkular-inventory/caches) and newly also metrics

enabling travis cache

---

dist/pom.xml

EDIT: The `dev` profile will not create the zip and gz archives, if you need to have the old behavior use the `dozip` profile.
````bash
$cd dist
$mvn clean install -DskipTests -Pdozip
Total time: 41.865 s
$mvn clean install -DskipTests -Pdev
Total time: 22.411 s
````
=> 19.5 seconds saved
Here is what you can do in 19 seconds:
* https://www.youtube.com/watch?v=Yn9DpFY1X7o
* http://www.dailymail.co.uk/sport/olympics/article-3044119/Usain-Bolt-want-run-200-metres-19-seconds-fully-fit-impossible-beat-me.html
* https://www.youtube.com/watch?v=h2n9vPuzvj4
:smiley:

Dev profile will not create the Hawkular archives.

---

dist/src/main/resources/wildfly/patches/standalone.xsl

Two things:
* adding a new logging category for rest requests in inventory 
`-Dhawkular.log.inventory.rest.requests=DEBUG`
* adding a way to disable the agent subsystem by Java system property 
`-Dhawkular.agent.enabled=false`
Agent should not be disabled by default, it just makes things faster if you want to skip the discovery process and test something unrelated. I think, this could be handy also for the integration tests, where we are creating some entities in the inventory and then checking their presence. If the agent is disabled during this process it should remove a lot of side-effects caused by the agent feeding the resources/types/etc. during this tests.
(both params should be passed to the `standalone.sh` not to the mvn)

Adding two new handy parameters for hawkular

---

console/src/main/scripts/plugins/metrics/ts/urlList.ts

I don't have Safari to test this and I don't know why it submits an invalid form, but this should fix the issue (although may not be the ideal way to do so).

HAWKULAR-553 Additional condition to skip adding invalid URL

---

console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts

Fixes included:
- Toggling checkbox selects the row (and visually shows as selected);
- Clicking the row also selects it;
- Switch info bar to "N elements selected" when there's a selection;
- Select All toggles between selecting all and none;
- Enable/Disable multi operation button if there is/isn't a selection;
- Multi operation works on selected resources instead of all;

HAWKULAR-543 : Deployments "Select All" doesn't work

---

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesAlerts.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts
console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts
console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts

This is a preliminar refactor of alertsManager.ts in order to unify how Alerts API is being used from the UI.
We need to upgrade to Alerts 0.4.x and that has changes on the ui-services, but before to upgrade I think is good trying to simplify and use a consistent way to create triggers and fetch alerts.
There are some parts commented in datasources code as it will be simplify with 0.4.x when we can modify conditions in a single call.
@mtho11 and @jshaughn please, can you take a look ?
If this is ok, then tomorrow we can work upgrading 0.4.x + ui-services and fixing missing things on UI code.

Refactor alertsManager.ts

---

dist/docker-compose.yml
dist/docker/Dockerfile
dist/docker/README.adoc

Bump the versions for Docker for the Alpha5 release stream
- Hawkular to 1.0.0.Alpha5
- Cassandra to 2.2

Bump versions in the light of Alpha5

---

console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html
console/src/main/scripts/plugins/metrics/html/directives/alert.html
console/src/main/scripts/plugins/metrics/html/modals/alerts-web-setup.html
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts
console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts

This PR is focus on the Web Session metrics, as those are present in the page.
The original JIRA covers also Container Threads and Requests which are not shown.
So, I decided to support only alerts with visible metrics.
Please @mtho11 and @jshaughn take a look at this work and merge if you think is correct.

HAWKULAR-465 Add Web Tab alert dialog for Sessions

---

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesAlerts.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts
console/src/main/scripts/plugins/metrics/ts/metricsAppServerDetails.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts

Triggers and Conditions contexts are designed to be used at client level, so any additional field can be added easily there, as it doesn't affect into the alerts inference process.
please, @mtho11 take a look to see if it suits your requeriments for Alert Center API.

HWKALERTS-77 Add resourcePath into Trigger.context

---

console/src/main/scripts/plugins/metrics/ts/app-details/modals/appServerDeploymentsAddDialog.ts

Not all browsers append the "C:\fakepath\" and, for those who appended
if going back and forth, filename was getting cut by 12 chars every time

Fix Deployment file name cleaning

---

dist/src/main/resources/wildfly/patches/standalone.xsl
modules/end-to-end-test/pom.xml
pom.xml

Updated version property (with srcdep)
Also, removed the "org.apache.cassandra" logger definitions (no longer needed)

HAWKULAR-629 Upgrade to the new embedded Cassandra version (without log conflicts)

---

pom.xml

With the upgrade of bus v0.7.0 alerts needed to be aligned and use same API.
I've upgraded into 0.5.x and using srcdeps to point specific commit as we have not finished the 0.5.0 version yet.

Bump alerts to 0.5.x using srcdeps

---

console/src/main/scripts/plugins/accounts/html/organization-accept-invitation.html
console/src/main/scripts/plugins/accounts/html/organizations.html
console/src/main/scripts/plugins/accounts/less/accounts.less
console/src/main/scripts/plugins/accounts/ts/invitation.ts
console/src/main/scripts/plugins/accounts/ts/organizationMembership.ts
console/src/main/scripts/plugins/accounts/ts/organizations.ts
console/src/main/scripts/plugins/accounts/ts/persona.ts
console/src/main/scripts/plugins/metrics/less/metrics.less
console/src/main/webapp/index.html

Refined:
- Account switch 
- Accept invitation screen
- Feedback messages
Pending, for Juraci:
- When changing user role: show feedback success via toastr "User role successfully changed." Thus, you can remove the check icon after transferring.
- Loading should be the patternfly style: https://www.patternfly.org/widgets/#spinner
- Select should be patternfly style: https://www.patternfly.org/widgets/#bootstrap-select
- The feedback message in the modal when transferring ownership should contain the line below: “This action can’t be undone.” See modal delete url for reference

HAWKULAR-680 and organizations improvements

---

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts

This PR implements sorting from server side.
There are pending tasks to be done, for example, it is needed to combine pagination + sorting.
This is not yet implemented but instead to send a full large commit I'm going to send small ones.
On this way, it is easy to cut for the MS having things on a stable way.
@mtho11 can you take a look, please ?
Thx.

Add partial sorting on AlertsCenter

---

dist/src/main/resources/wildfly/patches/standalone.xsl

The use of ${jboss.server.data.dir} in a URI inside of standalone.xml is
a problem. The windows path backslashes are not valid.  Instead, use the
new org.hawkular.data.dir, defaulting back to the jboss property.  This
allows windows users to set the new property on the command line to
bypass the issue (or to use a directory not under the jboss server,
if desired)

HAWKULAR-557 Broken on Windows

---

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts

Last minor to have updated the same style as presented by UI for "View Alerts" umbrella.
There are pending things not yet implemented as we need support from backend:
- Sorting by trigger context is not yet supported in Alerts.
- Comments are only supported on transition state but not as generic ones per alert, this need also support on the backend.
@mtho11 please, if you can take a look and merge, with this the AlertCenter has a good progress in this area.
I'm going to move into Hawkular Alerts to add these pendings services, back into UI when ready.

Move alerts actions into a dropdown

---

dist/src/main/resources/wildfly/patches/standalone.xsl

Accounts is now handling this option: if provided, use it. Otherwise, build the URL based on the bind parameters.

HAWKULAR-648 - Removed auth-server-url-for-backend-requests

---

console/src/main/scripts/plugins/directives/subtab/html/subtab.html
console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts
console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts

Small PR to introduce tabs into AlertCenter.
@jshaughn can you review ? 
You can follow same pattern for the definitions, I used a simple way (similar as metrics) as we are only have two main sections, so no need to create a main controller for tabs, we can move between sections via router parameters (as it works for the datepicker filter).

Add tabs for AlertsCenter

---

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts
console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts
console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts

Non-bucketed calls are still not moved as it needs further changes. Also
moved all calls to formatBucketedChartOutput to use method from service.

Move calls to (bucketed) metrics all to MetricsService

---

console/src/main/scripts/bower.json
console/src/main/scripts/plugins/metrics/html/modals/delete-resource.html
console/src/main/scripts/plugins/metrics/less/metrics.less
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts

Changes:
- Update hawtio-template-cache so it works with ng-animate;
- Reduce the feedback message dialog content to: "Are you sure you want
to delete <strong>[URL]</strong>? This action cannot be undone.";
- Animate removal of the url box from the list;
- Remove the toastr success notification;

HAWKULAR-668 : Improve Delete URL interaction

---

modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java
modules/avail-creator/src/main/java/org/hawkular/component/availcreator/MetricReceiver.java

HAWKULAR-751 Avail Creator: server runs out of memory under heavy load
MetricReceiver performance enhancements
Under heavy load, this bean was a slow consumer and made the system run out of memory.
In order to consume messages faster:
- disable transaction support
- use a shared ObjectMapper
- navigate Json with Jackson API
- don't call the publisher if nothing to send

HAWKULAR-751 Avail Creator: server runs out of memory under heavy load

---

console/src/main/scripts/bower.json

This is because we are doing some breaking changes on master now.

Move charts back to 0.5.19 instead of snapshot

---

console/src/main/scripts/plugins/topology/ts/d3Setup.ts
console/src/main/scripts/plugins/topology/ts/topologyGlobals.ts
console/src/main/scripts/plugins/topology/ts/topologyPlugin.ts

Injections are now handled with ng-annotate during gulp build, so they can be removed from .ts files. Be careful about variable names , as they should have same name as is registered in module. In this case HawtioNavBuilderProvider was named builder which was not recognized with ng-annotate and threw error.

HAWKULAR-500

---

pom.xml

Previous alerts 0.6.0-SNAPSHOT was not ready to integrate in hawkular.
So, unexpected issues could happen with alerts component.
This srcdeps version is our last stable version prior of release.

Fix alerts 0.6.0 srcdeps version

---

console/src/main/scripts/plugins/directives/topbar/html/topbar.html
console/src/main/scripts/plugins/topology/html/index.html
console/src/main/scripts/plugins/topology/ts/topologyPlugin.ts

Displaying the spinner only during the call of `getData()`. If the inventory is empty, "No Data" is displayed instead of the spinner.
Also making the topology graph visible by default.

HAWKULAR-788 - Topology view keeps showing the waiting spinner when no resource.

---

pom.xml

Required to make WS Ops work with latest inventory.

Update to Command GW 0.10.3.Final

---

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html
console/src/main/scripts/plugins/metrics/html/partials/trigger-alerts-sidebar.html
console/src/main/scripts/plugins/metrics/html/url-response-time.html
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts
console/src/main/scripts/plugins/metrics/ts/metricsAppServerDetails.ts
console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts
console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts
console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts
console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts
pom.xml

- Replace using multiple triggerId queries with a single resourceId-tag query,
when fetching alerts in the detail views.
- We should avoid using IDs for any more than as a unique identifier.
- We may now be able to make triggerIds UUIDs and not be comprised of
resourceIds, which would be nicer when we use them in route urls.
- store alertType on context for easy, consistent, non-hardcoded use.
Also:
- Bump root pom to Alerts 0.6.0.Final
- Do not use context.description for sorting the AC alerts list
- Instead, use the new native trigger.description support offered by alerts
- reason 1: context.descroption was not being set on all triggers
- reason 2: trigger description is editable. The value presented on screen
may not be the value used for sorting.
- reason 3: context bloat
- Tweak JVM …

Hawkular-571 Alert Query by Resource

---

console/src/main/scripts/plugins/directives/topbar/html/topbar.html
console/src/main/scripts/plugins/metrics/html/agent-installer.html
console/src/main/scripts/plugins/metrics/less/metrics.less
console/src/main/scripts/plugins/metrics/ts/agentInstaller.ts
console/src/main/scripts/plugins/metrics/ts/globalController.ts
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
dist/assembly.xml
dist/pom.xml
modules/hawkular-wildfly-agent-download/src/main/java/org/hawkular/component/wildflymonitor/WildFlyAgentServlet.java

* extending the agent servlet to be able to serve the agent installer. The servlet takes couple of query params and puts their values into property file stored inside the jar so the user then can just download the jar and run 
```bash
java -jar agent-installer.jar
```
* Agent installer UI page with some form fields that are actually mapped into those properties from ^
(the page is by default hidden under the experimental mode)

Hawkular 806

---

console/src/main/scripts/plugins/directives/subtab/html/subtab.html
console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts
console/src/main/scripts/plugins/directives/topbar/html/topbar.html
console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html
console/src/main/scripts/plugins/metrics/html/app-server-list.html
console/src/main/scripts/plugins/metrics/html/directives/alert.html
console/src/main/scripts/plugins/metrics/html/url-list.html
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts

@mtho11, @ammendonca I've propagated the hkParams on urls where datepickers are used.
There is a pending question, if we should propagate hkParams across all views.
This PR only works on the case between alerts center, url, and app-server details, which I think is the most visible.
Please, let me know how it looks like, or feel free to take it as start point if you want to add some changes on top.

HAWKULAR-752 Propagate timeOffset params across views

---

console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html
console/src/main/scripts/plugins/metrics/html/directives/alert.html
console/src/main/scripts/plugins/metrics/html/triggers/event.html
console/src/main/scripts/plugins/metrics/html/url-alerts.html
console/src/main/scripts/plugins/metrics/html/url-availability.html
console/src/main/scripts/plugins/metrics/html/url-response-time.html
console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts
console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts
console/src/main/scripts/plugins/metrics/ts/metricsAppServerDetails.ts
console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts
console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts
console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
console/src/main/scripts/plugins/metrics/ts/triggers/eventTrigger.ts
modules/avail-creator/pom.xml
modules/pinger/pom.xml
pom.xml

Add alert generation for failed deployments.
- New src-deps versions for component enhancements to support this
- with mazz, enhanced bus-commons with better classloading/deserialization support for MDBs
- with mazz, enhanced command-gateway to support multiple commands on ws responses, now can notify UI and put a response on the bus
- enhanced alerts to consume ws deploy app response messages on bus and generate events
- Added new trigger definition on app-servers to fire on a failed deployment event
- note, also storing successful deployment events for future use/display
- Added new UI support for 'Event' trigger-type and DEPLOYMENT_FAIL alert-type
Also:
- fixed time-window bug in getAlerts query for some trigger types
- make bus-commons dep provided (by nest) for pinger
- make …

Hawkular-464 Deployment Failure Event Alerting

---

console/src/main/scripts/package.json

It seems something started causing issues with non-numeric bower versions.

Update Bower to version 1.6.3.

---

console/src/main/scripts/gulpfile.js

File deletion may cause trouble, as multiple changes will trigger simultaneous builds,
which often end up causing gulp to fail (exit) due to trying to operate on deleted files.
With this change the delete only happens if a build is not in progress already.

Enable file deletion only if build not in progress

---

console/src/main/scripts/bower.json
console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
console/src/main/scripts/plugins/metrics/html/alerts-center-list.html
console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html
console/src/main/scripts/plugins/metrics/html/partials/trigger-alerts-sidebar.html
console/src/main/scripts/plugins/metrics/ts/filters/truncateFilter.ts
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts

Filter usage:
{{ "some text" | truncate : <length> : <words> : <left|right|middle> | <separator> }}
- length: the truncated size (defaults to 15)
- words: keep words intact (defaults to false)
- left|right|middle: where to truncate (defaults to left)
- separator: the separator char/string (defaults to '...')

Replace truncate libraries with single custom filter

---

console/src/main/scripts/bower.json
console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html
console/src/main/scripts/plugins/metrics/html/app-server-list.html
console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/modals/appServerDatasourcesAddDialog.ts
console/src/main/scripts/plugins/metrics/ts/app-details/modals/appServerDatasourcesEditDialog.ts
pom.xml

With the renaming made in the agent, it is now possible/easier to just
use the name instead of playing around with trimming the id or the name.
Also update to latest commit of ui-services required by Update DS.

Use resources "name" instead of playing with "id"

---

console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts

Not using fixed index as it can easily get broken, using instead a list of experimental tabs.

Better fix to Experimental Mode tabs enable/disable

---

pom.xml

This is to pull the correct version of `hawkular-commons` and other components.

Upgrade to inventory 0.10.1.Final.

---

console/src/main/scripts/plugins/directives/subtab/html/subtab.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-overview.html
console/src/main/scripts/plugins/metrics/html/directives/alert-info.html
console/src/main/scripts/plugins/metrics/ts/alerts.ts
console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts
console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts
console/src/main/scripts/plugins/metrics/ts/directives/fileReadDirective.ts
console/src/main/scripts/plugins/metrics/ts/urlAvailabilityDetails.ts
console/src/main/scripts/plugins/metrics/ts/urlResponseTimeDetails.ts

- Remove useless, error throwing resource query on alert center pages;
- Fix links to Trigger definitions on Overview screen;
- Fix HTML (missing closing div) on alert-info directive;
- HAWKULAR-742 : Handle switch persona at URL details pages;
- Cleanup some console.log messages;

UI fixes for M8

---

console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts

The fix for this may also improve accuracy for non-NaN values because we
weren't handling 0 values correctly.

Hawkular-887 NaN alert values

---

pom.xml

I was able to manually replicate by:
cloning the repo and running:
```bash
git pull https://github.com/hawkular/hawkular-alerts.git d105e2ba1ee28eb19f4573aa50065468d2bdaaa2:d105e2ba1ee28eb19f4573aa50065468d2bdaaa2
```
```bash
[ERROR] Cloning into '/home/jkremser/.m2/repository/../dependency-sources/alerts'...
From https://github.com/hawkular/hawkular-alerts
* [new ref]         d105e2ba1ee28eb19f4573aa50065468d2bdaaa2 -> d105e2ba1ee28eb19f4573aa50065468d2bdaaa2
warning: refname 'd105e2ba1ee28eb19f4573aa50065468d2bdaaa2' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,
git checkout -b $br $(git rev-parse ...)
where "$br" is somehow empty and a 40-hex ref …
```

Fixing the 'refname abcdef is ambiguous' issue when building the alerts with srcdep plugin.

---

console/src/main/scripts/gulpfile.js

The new dist hawkular path has one less hawkular-<version> directory

Adapt gulp-watch dist target to new location

---

modules/pinger/src/main/java/org/hawkular/component/pinger/Pinger.java

Each time the `ping()` method was invoked, it created a new client within the try-with-resource block... it implements the closeable so it also closed the client and client closes the connection pool of the `PoolingHttpClientConnectionManager`
The issue happened if 2 pings were done in parallel. 2 http clients were created, but they had 1 shared connection pool. Once the first client finished his work, it closed the connection pool and the 2nd client failed with the exception.
Solution is to recycle the Http client and close the connection (using the try-with-resource) idiom. Other option would be make the ping method synchronized (or some it's part), but this should be faster.
Note to myself: migrate to [okhttp](https://github.com/square/okhttp) and use the async approach, currently the …

HAWKULAR-911 - Pinger error when adding a URL

---

console/src/main/scripts/plugins/metrics/ts/alerts.ts
console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts
console/src/main/scripts/plugins/metrics/ts/triggers/availabilityTrigger.ts
console/src/main/scripts/plugins/metrics/ts/triggers/rangeByPercentTrigger.ts
console/src/main/scripts/plugins/metrics/ts/triggers/rangeTrigger.ts
console/src/main/scripts/plugins/metrics/ts/triggers/thresholdTrigger.ts

Ensure that potential evalTimeSetting values are well-handled by making 0
an explicit indicator of default dampening.

HAWKULAR-912 Fix issue with alert dampening display

---

modules/end-to-end-test/pom.xml

Currently the only itests that are being run during the travis build are the ones for the inventory. This PR enables the itests also for the end-to-end test (this guy: http://git.io/vuzjw)

Enabling the end-to-end integration test.

---

console/src/main/scripts/bower.json
console/src/main/scripts/plugins/metrics/html/agent-installer.html
console/src/main/scripts/plugins/metrics/less/metrics.less
console/src/main/scripts/plugins/metrics/ts/agentInstaller.ts
console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts

Currently it's broken and it's downloading the module zip file instead of the installer jar, because the server-side was slightly changed.
This change:
* changes the url that was changed in the servlet (`/hawkular/wildfly-agent/download?installer=true` -> `/hawkular/wildfly-agent/installer`)
* removes the 'Required' form section and makes everything optional
* adds the copy button that will copy the `java -jar foo..` command into user's clipboard
* removes the version information that is no longer valid
NOTE1: this page will be probably different in the future this is a hot fix to have something working for the next alpha
NOTE2: I wasn't able to make the [zeroclipboard](https://github.com/zeroclipboard/zeroclipboard) + [ngClip](https://github.com/asafdav/ng-clip) working when …

hot-fixing the install agent page 

---

pom.xml

depends on alpha9 version of base components

Up to Alerts 0.8.2.Final

---

console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-datasources-edit.html

This is related to an issue with pfSelect not updating when ng-options change, thus we only render when we have the data.
angular-patternfly issue @ https://github.com/patternfly/angular-patternfly/issues/177

HAWKULAR-980 : Show drivers in Edit DS wizard only when retrieved

---

console/src/main/scripts/plugins/metrics/html/app-details/app-server-details.html

Since the server overview already has the operation in the proper place, removing the temporary solution.

HAWKULAR-986 : Remove "Export JDR" button from App Server tabs template

---

modules/end-to-end-test/pom.xml
modules/hawkular-api-parent/hawkular-rest-api/pom.xml
modules/hawkular-api-parent/hawkular-rest-api/src/main/webapp/WEB-INF/web.xml
modules/hawkular-api-parent/hawkular-rx/pom.xml
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/common/AbstractHttpCommand.java
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/common/CommandLogger.java
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/hawkular/CreateUrlCommand.java
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/hawkular/DeleteUrlCommand.java
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/inventory/CreateMetricCommand.java
modules/hawkular-api-parent/hawkular-rx/src/main/java/org/hawkular/rx/commands/inventory/CreateResourceCommand.java
modules/hawkular-api-parent/hawkular-rx/src/main/resources/config.properties
modules/hawkular-api-parent/hawkular-rx/src/test/resources/config.properties

The timeouts are there for all the hystrix commands. Some commands are simple and some are compound and call multiple rest endpoints (`{Create|Delete}UrlCommand` performs 3 calls (2 in parallel, tough)). The timeouts can be tuned per command or globaly, or turned off. It's done via the [archaius](https://github.com/Netflix/archaius) config library, it supports sysprops, config files and also zookeeper, etcd and other backends with all the overriding logic.
I've already increased the timeout because I saw a failure in travis, but it's happening again so lets turn it off for the itests.
Second part is exposing the metrics from hystrix commands as an event stream - https://git.io/vgfJe
This should be available on `http://localhost:8080/hawkular/api/hystrix.stream` and it can be visualized by …

Not using the hystrix command timeouts in i-tests that are run by travis

---

console/src/main/scripts/plugins/metrics/html/url-availability.html
console/src/main/scripts/plugins/metrics/html/url-response-time.html
console/src/main/scripts/plugins/metrics/ts/directives/alertSetupNotificationDirective.ts

Also fix the path to the directive template.
It should evaluated if this directive, inline notification, is to be used. If not, remove it completely from alerts.

HAWKULAR-996 : Remove hk-alert-notification from URL details page

---

console/src/main/scripts/plugins/metrics/html/url-response-time.html
console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts
console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts
console/src/main/scripts/plugins/metrics/ts/urlList.ts
console/src/main/scripts/plugins/metrics/ts/urlResponseTimeDetails.ts

Metrics have changed the way percentiles are requested and the way they
are sent. This was causing URL Percentil 95th to be shown as 0.
Also change chart type for RT from deprecated "hawkularmetric" to "line"

HAWKULAR-1009 : Adapt to metrics API change to percentiles

---

console/src/main/scripts/plugins/metrics/less/metrics.less

The fill should only be applied to sparklineArea and not to sparklineLine

HAWKULAR-1019 : Fix sparkline chart when c3-danger class is applied

---

console/src/main/scripts/plugins/metrics/html/directives/explorer/side-filter-container.html
console/src/main/scripts/plugins/metrics/html/explorer.html
console/src/main/scripts/plugins/metrics/less/metrics.less
console/src/main/scripts/plugins/metrics/ts/directives/explorer/sideFilterContainerDirective.ts
console/src/main/scripts/plugins/metrics/ts/directives/navTree.ts
console/src/main/scripts/plugins/metrics/ts/inventoryExplorer.ts
console/src/main/scripts/plugins/metrics/ts/viewController.ts
console/src/main/webapp/index.html

When recursive children are loaded slash needs to be hashed to %2F. When metrics are loaded for selected resource whole path from feed id should be taken, not only id.

HAWKULAR-1053 change loading of recursive children and metrics

---

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts

When a periodic refresh occurred, the deployments table was selecting
all the items in the table. This fixes that behavior.

HAWKULAR-1059 : Fix deployments select on refresh

---

console/src/main/scripts/bower.json
console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-transactions.html
console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html
console/src/main/scripts/plugins/metrics/html/directives/datasources/detail.html
console/src/main/scripts/plugins/metrics/html/directives/overview/status-overview-item.html
console/src/main/scripts/plugins/metrics/html/directives/overview/status-overview.html
console/src/main/scripts/plugins/metrics/html/directives/url-list/item.html
console/src/main/scripts/plugins/metrics/html/explorer.html
console/src/main/scripts/plugins/metrics/html/url-availability.html
console/src/main/scripts/plugins/metrics/html/url-response-time.html
console/src/main/scripts/plugins/metrics/less/metrics.less

Update hawkular charts to 1.0.0
Some screenshots: https://drive.google.com/open?id=0BxM9OWSBhvYoQ01lb1pjQVM5MnM
Note that alternatives to ``sparkline`` charts reserve some space on the left for y axis label.
@mtho11 could you please review?

Update hawkular charts to 1.0.0
