hawkular/hawkular

ui/console/.gitignore, ui/console/pom.xml
So it doesn't mess with the maven stuff ppalaga did.
=> Moving the node build to the target dir

kettle/docker/Dockerfile, kettle/docker/README.adoc, kettle/pom.xml
Initial CI/CD work to get hawkular in Docker form
=> Add support for building Hawkular as Docker image

modules/pinger/pom.xml, modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
Update pinger for metrics sending. Needs a bit more work
=> Update pinger for metrics sending. Needs a bit more work

ui/console/src/main/scripts/bower.json, ui/console/src/main/webapp/index.html
+ Fix for the bower dependency
=> Added alerts dep - d3 plugin to scripts

.travis.yml
In the spirit of consuming the official binaries I redid the docker image build process, pulling dist zip from maven repo
=> Add trigger for Docker hub image build

.travis.yml
Docker image now lives in hawkularorg repo: https://registry.hub.docker.com/u/hawkularorg/hawkular/
Update trigger url to reflect new location.
=> Update DockerHub trigger url

ui/console/pom.xml, ui/console/src/main/java/org/hawkular/console/configuration/PushStateConfigurationProvider.java
Once we know all console pages we should state the valid whitelist in the PushStateConfigurationProvider class.
=> HAWKULAR-44: Made refresh work with console on wildfly

ui/console/src/main/scripts/gulpfile.js, ui/console/src/main/scripts/package.json
Conflicts:
ui/console/src/main/scripts/gulpfile.js
=> HAWKULAR-46: Added handling of src files to gulp

.travis.yml
=> Move to a more official namespace

modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
Hawkular-Metrics has changed its api which makes the pinger fail.
This PR changes the data sent to follow the change in metrics.
=> Get pinger back to work after metrics-api changes

modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
HAWKULAR-49  Do not start a ping on add, as this may block the add()
method for too long. Instead ping every 20 seconds.
=> HAWKULAR-49  - prevent timeout on add()

ui/console/src/main/scripts/bower.json
Update bower to latest hawtio libs and allow hawkular-ui-components to auto update (since we version and control it).
=> Update hawtio bower packages to latest

ui/console/src/main/webapp/index.html
Hovering over Hawkular logo shows version of the 1st ui-components js file. To inspect all files, please open the page (elements) in the console (inspect) and check the versions in the comment at the bottom of the page.
=> HAWKULAR-53: Showing ui-components sha in console

ui/console/pom.xml, ui/console/src/main/scripts/plugins/includes.ts
* Fixed the Node.js stuff executed twice.
* Fixed the TS error in unused TS code.
=> Fixed couple of maven build issues

ui/console/src/main/scripts/bower.json
via hawkular-ui-components ^0.3.1 (a new minor version).
=> Adjust bower for ui to pull in new inventory stuff 

kettle/pom.xml, kettle/src/main/scripts/standalone.xsl, modules/end-to-end-test/pom.xml, modules/end-to-end-test/src/test/groovy/org/hawkular/integration/test/Scenario1.groovy, modules/pinger/pom.xml, modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/NotificationReceiver.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java
this is pr #72 + the code responsible for creating the tenant, environment and resourceType. It conceptually fits the best to the Pinger.
This can be merged after the PRs in hawkular/ui-{services|components} are merged
=> Hwkinvent-24 - port pinger to new inventory bus + setup work

ui/console/pom.xml
Original request from Lukas https://github.com/hawkular/hawkular/pull/70 but complex merges made this one liner much easier to just commit.
=> Update maven UI frontend to support maven 3.3.1.

README.adoc
HAWKUlar-107 update documentation and link to web site.
=> HAWKULAR-107 update documentation

ui/console/src/main/scripts/bower.json
fix bringing in older version of lodash with hawt.io ui bower package.
=> Add additional bower resolution to fix hawtio ui conflict

modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java, modules/pinger/src/test/java/org/hawkular/component/pinger/test/PingerTest.java
Moving the code for inventory initialization from pinger startup method to UI.
this PR is related to https://github.com/hawkular/hawkular-ui-components/pull/109
=> HWKINVENT-38 

kettle/pom.xml, modules/avail-creator/pom.xml, modules/end-to-end-test/pom.xml, modules/pinger/pom.xml, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/NotificationReceiver.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingStatus.java, modules/pinger/src/main/java/org/hawkular/component/pinger/Pinger.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingerConfiguration.java, modules/pinger/src/test/java/org/hawkular/component/pinger/test/PingerTest.java, pom.xml
This is a preparation for https://github.com/ppalaga/hawkular/commits/HAWKULAR-173 which is not 100% ready yet. It was agreed with @theute that I can send the dependency management change before he submits his "Kettle dissolution" and that he will rebase.
=> Manage dependencies in the top level pom.xml

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/accounts/plugins/accounts/ts/accountsPlugin.ts, ui/console/src/main/scripts/plugins/directives/plugins/topbar/ts/topbarServices.ts, ui/console/src/main/scripts/plugins/directives/plugins/topbar/ts/topbarTypes.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAvailabilityPage.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsResponsePage.ts
successor of https://github.com/hawkular/hawkular/pull/114
=> HWKINVENT-38 switching to the inventory 0.0.2-SNAPSHOT (rebased)

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/less/metrics-main.less, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts
instead of being repeated in table body.
=> HAWKULAR-256 Move last updated timestamp to header 

dist/src/main/resources/wildfly/patches/standalone.xsl
set console log level appropriately
use xsl:choose, not xsl:if
=> add new hawkular component log categories

pom.xml
don't merge untill the artifacts are in the mvn repo (https://repository.jboss.org/nexus/content/groups/public-jboss/org/hawkular/inventory/inventory-api/0.0.7/)
EDIT: it can be merged
=> Inventory version bump.

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/inventory/plugins/inventory/ts/inventoryPlugin.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsPlugin.ts
Fixed:
* Bower resolution error
* Incorrect module name for charts in the console
=> UI: Fixed build issues

modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java, modules/end-to-end-test/pom.xml, modules/end-to-end-test/src/test/groovy/org/hawkular/integration/test/AbstractTestBase.groovy, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingerConfiguration.java
=> HAWKULAR-106 availability metric is not collected for non-localhost

dist/src/main/resources/wildfly/patches/standalone.xsl
@theute  , could you please review this one? If approved, I'll also merge the following, as the changes are identical: https://github.com/hawkular/hawkular-accounts/pull/27
=> HAWKULAR-269 - Using jboss.bind.address for KC server URL

modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java, modules/end-to-end-test/src/test/groovy/org/hawkular/integration/test/Scenario1ITest.groovy, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingerConfiguration.java
@jsanda  could you please review and eventually propose fixes where I have not guessed the new paths?
This is more like a highlighting of places that need to be fixed than real fixes. Sorry, I was not able to get the real old -> new mapping from https://github.com/hawkular/hawkular-metrics/releases/download/0.3.3/Metrics_REST_API_0.3.1_vs_0.3.3.pdf
=> HAWKULAR-284 Adapt pinger, avail creator and e2e test to metrics 0.3.4

pom.xml, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts
also when creating and deleting the metrics, now we are doing it in parallel with the `$q.all`
=> HWKINVENT 45 - Deleting metrics before deleting the resource from inventory

dist/src/main/resources/wildfly/patches/standalone.xsl, pom.xml
move to agent 0.0.8; provides more unique resource names for those that are the same across multiple servers
=> move to agent v0.0.8

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-server-list.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/availability.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerList.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAvailabilityPage.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsPlugin.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsResponsePage.ts
Fix the availability refresh button(it was using  an old method name) and Make the salutation filter just upper case the first character because some names may want to preserve other case in the name.
=> HAWKULAR-300 Fix the availability refresh button. 

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/alerts-view.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/alerts.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/app-server-details.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-server-list.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/availability.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/response-time.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/less/metrics-main.less, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAlerts.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerList.ts, ui/console/src/main/webapp/index.html
Other enhancements:
- Upgrade Patternfly to 1.2.1;
- Move to first position and rename "Alerts" tab to "All Alerts";
=> HAWKULAR-253: Add "No Alerts" and "No Application Servers configured" panels

ui/console/src/main/scripts/bower.json
Incorporate changes from hawkular-charts.
=> HAWKULAR-295 Fix Availability Chart interval

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/add-url.html
on Availability and Response Time.
=> HAWKULAR-304 UXD Label Changes to show 'Current' time range 

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/response-time.html
Looks like someone changed the LESS stylesheet colors without updating the html.
=> HAWULAR-305  Fixed Chart Legend style colors are now gone.

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-server-list.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/less/metrics-main.less, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerList.ts
Other changes:
- Remove Alerts box, replace it by unknown state;
- Increase number of app servers per page to 10;
- Put back toastr styles;
=> HAWKULAR-307: Fix app server list when no app server (and type) configured

ui/console/src/main/scripts/plugins/accounts/plugins/accounts/html/inactivityModal.html
=> HAWKULAR-241 

modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/TraitsPublisher.java
tries to write to it is a valid scenario and should not result in an
unhandled exception.
=> [HAWKULAR-299] A resource disappearing asynchronously while traits publisher

pom.xml
HAWKULAR-321 this provides hostname as a resource configuration property on the top level server resource
=> move to agent .10

modules/end-to-end-test/src/test/groovy/org/hawkular/integration/test/Scenario1ITest.groovy
=> HAWKULAR-337 Handle the race condition between WildFly Agent and End to

ui/console/src/main/webapp/index.html
=> HAWKULAR-185 adding id for logout link

modules/end-to-end-test/src/test/groovy/org/hawkular/inventory/rest/test/InventoryITest.groovy
=> Cover filtering of resources by resourceType in invetory integration

dist/assembly.xml, dist/pom.xml, pom.xml
@jmazzitelli would you please review?
=> Upgrade to Metrics 0.4.0.Final and Hawkular Commons 0.1.0.Final

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/response-time.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/less/metrics-main.less
Make changes to the chart legend title on the metrics response page with the latest UXD chart changes.
=> Hawkular 213 chart legend and bump hawkular-charts version.

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/inventory/plugins/inventory/ts/inventory.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/addUrlPage.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsPlugin.ts
(when calling HawkularInventory.Something.something(), because it's not needed anymore)
=> Removing the tenantId parameter 

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/app-server-details.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-alerts.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-datasources.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-deployments.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jms.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-transactions.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-web.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerAlertsDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerJmsDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerJvmDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerTransactionsDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerWebDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerDetails.ts
Includes other (needed) changes
Included changes for dealing better with tabs and splitting the Details controllers
=> HAWKULAR-217 : Initial implementation for JVM Metrics tab

dist/src/main/resources/configuration/hawkular-realm-for-dev.json
ui-services REST tests need it to work
=> HAWKULAR-372 - adding special origins for PhantomJS browser

dist/assembly.xml, dist/pom.xml
Docker files still need to change
=> HAWKULAR-384 Changed root directory name to hawkular-VERSION

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/alertsManager.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAlerts.ts
The auto-resolve feature implemented according to this comment:
https://issues.jboss.org/browse/HAWKULAR-367?focusedCommentId=13083716&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13083716
=> HAWKULAR-367: Consolidate Multiple Alert firings

pom.xml
- notification bug fix on WF9
- support standard props for cassandra configuration
=> Up Alerts from 0.2.0.Final to 0.2.1.Final

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerJvmDetails.ts
=> Change the mulit-line chart colors for JVM chart.

ui/console/src/main/scripts/bower.json, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-deployments.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html
And remove Alerts Settings from app detail screens.
=> New hawkular charts and Alert Settings.

ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/app-server-details.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-datasources.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-server-list.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsAppServerDetails.ts, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/metricsPlugin.ts
Fixes:
- Only render DS charts if they are visible for perf reasons;
- Fix DS charts legend to match colors;
=> HAWKULAR-410 : Make app server details page bookmarkable + misc fixes

dist/src/main/resources/wildfly/patches/standalone.xsl, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/html/app-details/detail-jvm.html, ui/console/src/main/scripts/plugins/metrics/plugins/metrics/ts/app-details/appServerJvmDetails.ts
Changes to ge the MaxHeap data from Gauges 
Plus some shorter intervals for some data.
=> HAWKULAR-411 Changes around handling of max-heap

dist/assembly.xml
@pilhuhn  , this PR should solve the issue you reported via email :)
=> Removed extra dependency sets for Accounts KC event listeners.

console/src/main/java/org/hawkular/console/configuration/PushStateConfigurationProvider.java
Also, move the redirect log to DEBUG level
=> HAWKULAR-441 : Redirect to console index.html only on hawkular-ui* paths

console/src/main/scripts/.editorconfig, console/src/main/scripts/plugins/metrics/ts/metricsResponsePage.ts
=> Fix the line length in metricsResponsePage.ts and add lincense header to

modules/avail-creator/pom.xml, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/Log.java, modules/pinger/pom.xml, modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, pom.xml
@Jiri-Kremser could you please review?
=> Upgrade to hawkular-parent 18

console/src/main/scripts/plugins/metrics/ts/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts, dist/assembly.xml, dist/pom.xml, modules/avail-creator/pom.xml, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailDataMessage.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/Log.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/MetricReceiver.java, modules/pinger/pom.xml, modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricDataMessage.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, pom.xml
This PR has updated alerts to 0.3.0.Final-SNAPSHOT for testing with latest bus 0.2.1-SNAPSHOT and other dependencies.
It has also commits for gson -> jackson replacement in hawkular/modules.
It replaces also the use of ObjectMessage from bus inside hawkular/modules.
=> Alert 0.3.0.Final-SNAPSHOT

console/src/main/webapp/time-out.html
Adding it to the project. Juraci will add the logic.
=> HAWKULAR-444 Time out screen

console/src/main/scripts/plugins/metrics/html/availability.html, console/src/main/scripts/plugins/metrics/ts/metricsAvailabilityPage.ts
- Replace template logic for downtime duration by controller function;
- Replace window usage by $window;
- Replace moment usage by $moment;
- Replace several ['parameter'] usage by dot notation, .parameter;
- Remove unused alertResolve function;
=> URL Availability Code Review Changes

pom.xml
this should fix the error in the server.log shortly after WF startup (when feeding the resources with '/' in id)
=> Upgrade inventory to 0.2.0.Alpha2

dist/assembly.xml, dist/pom.xml, pom.xml
Upgraded needed to solve last blocker issue found yesterday night
=> Upgrade alerts to 0.3.1.Final

console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
=> Fix the app-server details link

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html, console/src/main/scripts/plugins/metrics/html/availability.html, console/src/main/scripts/plugins/metrics/html/url-list.html
Move to a static version of hawkular-charts for release
=> Charts 0.4.9

console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
Overzealous refactoring without using 'this'.
=> HAWKULAR-492 Hawkular UI Url detail Alerts Tab Nothing shows up

console/src/main/scripts/plugins/metrics/html/app-details/alerts-setup-jvm.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html, console/src/main/scripts/plugins/metrics/ts/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, pom.xml
@ammendonca please test and approve this PR if it's ok.
=> Adding alerts to JVM page

dist/src/main/resources/wildfly/patches/standalone.xsl
there are more that we need to designate counter, but rather than flip them all right before release, I'll just do these three
h-434 is the jira where we need to go through and mark all the counters that should be counters
=> turn three metrics into counters

dist/src/main/resources/wildfly/patches/standalone.xsl
HAWKULAR-434 - change metrics to their more appropriate type of "counter"
Not expecting to merge this until after the alpha3 release today, unless UI folks want this now. I'll leave it up to others as to when this should be merged
=> HAWKULAR-434 - change more metrics to counters

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts
=> HAWKULAR-458 Deployments Detail Screen: Hook up New Agent Operations

console/src/main/webapp/index.html
We have agreed on the rule to not use data-* prefix on our Angular code
=> Remove data-* angular tags

console/src/main/scripts/gulpfile.js
Please merge only after approval of @jshaughn
=> HAWKULAR-254 Fixing quote issue with windows build

dist/docker-compose.yml, dist/docker/Dockerfile, dist/docker/README.adoc, dist/pom.xml
More docs.
Part of that could be replicated/moved into the Web site I guess.
=> Update the Dockerfile to Alpha4 and add more documentation

dist/assembly.xml, dist/pom.xml, dist/src/main/resources/wildfly/patches/standalone.xsl, modules/end-to-end-test/pom.xml, modules/pinger/pom.xml, modules/pinger/src/main/webapp/WEB-INF/jboss-all.xml, modules/pinger/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, pom.xml
+ reflecting the changes in Maven module names in the inventory
=> Inventory version++

pom.xml
@vrockai , could you please review this?
=> HAWKULAR-520 - Bumped accounts

modules/end-to-end-test/src/test/groovy/org/hawkular/inventory/rest/test/InventoryITest.groovy, pom.xml
The tenant ID is now included in the paths returned from inventory REST.
~~Don't merge yet. This depends on https://github.com/hawkular/hawkular-inventory/pull/155~~
~~Once that is merged and a new release of inventory is ready, this PR needs to be updated with that new inv version before merging.~~
Ready to merge once CI passes.
=> [HWKINVENT-131] Update integration tests

console/src/main/scripts/bower.json
I'm not sure how this passed the Travis checks the first time...
=> Fix to bower ECONFLICT on angular version.

console/src/main/scripts/plugins/accessPortal/vendor/js/custom-cases.js, console/src/main/scripts/plugins/accessPortal/vendor/js/redhat_access_angular_ui.js, dist/assembly.xml, dist/pom.xml, dist/src/main/resources/wildfly/patches/standalone.xsl, modules/redhat-access-integration-backend/pom.xml, modules/redhat-access-integration-backend/src/main/java/org/hawkular/accesportal/backend/boundary/AttachmentEndpoint.java, modules/redhat-access-integration-backend/src/main/java/org/hawkular/accesportal/backend/control/JDRLocalReport.java, modules/redhat-access-integration-backend/src/main/java/org/hawkular/accesportal/backend/control/JaxRsActivator.java, modules/redhat-access-integration-backend/src/main/java/org/hawkular/accesportal/backend/control/RedHatAccessConfiguration.java, modules/redhat-access-integration-backend/src/main/java/org/hawkular/accesportal/backend/entity/SelectedFileForUpload.java, modules/redhat-access-integration-backend/src/main/webapp/WEB-INF/jboss-ejb3.xml, modules/redhat-access-integration-backend/src/main/webapp/WEB-INF/jboss-web.xml, modules/redhat-access-integration-backend/src/main/webapp/WEB-INF/web.xml, pom.xml
@lzoubek , would you please review this one? It's mostly based on your code, with minimal changes.
@theute / @pilhuhn , although I tested it locally, it would be interesting if you could test it as well, to check in other browsers/OSes. I tested in Firefox and Chrome for Fedora 22.
=> HAWKULAR-556 - Attach Hawkular's JDR to case.

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-deployments-add.html, console/src/main/scripts/plugins/metrics/html/modals/alerts-ds-setup.html, console/src/main/scripts/plugins/metrics/html/modals/alerts-jvm-setup.html, console/src/main/scripts/plugins/metrics/html/modals/alerts-url-availability-setup.html, console/src/main/scripts/plugins/metrics/html/modals/alerts-url-response-setup.html, console/src/main/scripts/plugins/metrics/less/metrics.less
Also corrected the Save button position in other modals.
=> HAWKULAR-370 Add Deployment modal

console/src/main/scripts/plugins/metrics/ts/urlList.ts
The reason why this is completely done in the UI is that a) this type of sorting is specific to the UI - no other client will most probably benefit from it and b) the UI merely defines the data to be used for sorting and then instructs the inventory to sort using it.
=> [HWKIVENT-133] Make the URLs sorted according to custom UI-specific rules.

console/src/main/scripts/bower.json
Pull in semi-responsive stuff + some bug fixes.
=> Upgrade to new bower version of charts 0.5.2.

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertSetupNotificationDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/fileReadDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/hkComponents.ts, console/src/main/scripts/plugins/metrics/ts/directives/paginationDirectives.ts, console/src/main/scripts/plugins/metrics/ts/filters/durationFilter.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsAppServerList.ts, console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts, console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts, console/src/main/scripts/plugins/metrics/ts/metricsResponseAlertForm.ts, console/src/main/scripts/plugins/metrics/ts/services/errorsManager.ts, console/src/main/scripts/plugins/metrics/ts/services/paginationService.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts
For reasons detailed here: https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/
=> ES6 'let' is the new 'var'

console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts
Missing fix for alerts refactoring.
=> Fix missing method on Alerts refactor

console/src/main/scripts/plugins/metrics/html/directives/alert-list.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts, console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
Another minor PR with small changes, just to continue to unifying API use before to upgrade to Alerts 0.4.x.
@mtho11 sorry to several PR instead of one, can you review this one ?
Thanks
=> Alerts fixes

console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
Minor refactor of actions.,
With this alertManagers.ts is the single point from UI to manipulate Alerts API, then future upgrades will be more easy to maintain.
=> Remove unused methods for actions manipulation

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts, pom.xml
Main tasks on this PR:
- Upgrade to Alerts 0.4.x.
- Upgrade to ui-services 0.8.2.
- Refactor UI services with new Alerts API.
- Add context support on triggers and conditions.
Please, @mtho11 and @jshaughn take a look on the PR to continue with other UI Alerts related tasks.
Thanks,
Lucas
=> Upgrade alerts 0.4.x

console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-deployments-add.html
This is a continuation of HAWKULAR-610 #472 because I needed to create a new branch.
=> Hawkular 610 File Chooser accept "*/*" for deployment add

console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html
Also fix showing selected rows in blue
=> HAWKULAR-507 : Close dropdown after selecting deployment action

pom.xml
go to accounts 1.0.14
go to alerts 0.4.1
go to latest bus/cmdgw/alerts
=> update some things

dist/src/main/resources/wildfly/patches/standalone.xsl
Reduce log noise when starting Hawkular with embedded C*
=> Set embedded C* default log level to WARN

console/src/main/scripts/plugins/directives/includes.ts, console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts, console/src/main/scripts/plugins/directives/topbar/html/topbar.html, console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/html/app-details/app-server-details.html, console/src/main/scripts/plugins/metrics/html/me.json, console/src/main/scripts/plugins/metrics/html/partials/url-alerts-view.html, console/src/main/scripts/plugins/metrics/includes.ts, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/EventNames.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts, console/src/main/scripts/plugins/metrics/ts/metricsGlobals.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts
More to come with Alert Center...
=> HAWKULAR-538 Alert center first pass

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/less/metrics.less
Mike, I saw some things that need fix:
- when selecting an item in the alerts list, the background is not getting dark blue. The class "hk-selected" needs to be applied in the <tr> element.
- In the alert details, after acknowledging an alert, the button is still active. Should be disabled as in the list.
- Popovers don't work on this screen.
=> HAWKULAR-538 Design adjustments

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsAvailability.ts, console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts, pom.xml
PR with:
- Preliminar work to introduce notifications API in AlertCenter.
- Unify alert queries on alertsManager.ts service.
@mtho11 please, could you take a look ?
=> Alerts center work

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
- Adapt new html template.
- Update transitions and comments.
- Refactor alertManagers.ts adding criteria and unifying the queries.
=> HAWKULAR-621 AlertCenter: complete alert details page

console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts
- Support for pagination.
- Basic client filtering.
Ordering and "resolved" filters are not yet implemented, but I prefer to push before the weekend.
@mtho11 please, can you review and merge ?
=> Add basic pagination into AlertsCenter

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts
PR with some fixes for glitches on the JVM and Web Alert modals.
=> HAWKULAR-690 Fix alerts message on cancelling modal

console/src/main/scripts/plugins/metrics/ts/globalController.ts, console/src/main/webapp/index.html
@pilhuhn this one is for your friend.
=> Enable experimental mode for some new features.

dist/assembly.xml, dist/pom.xml, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/MetricReceiver.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java, modules/pinger/src/test/java/org/hawkular/component/pinger/PingManagerTest.java, pom.xml
Use hawkular-metrics-component artifact
Remove double send from Pinger and Avail Creator
=> HAWKULAR-698 Upgrade to Hawkular Metrics Component

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
AlertsCenter:
- Include generic comments on alert on every state.
- Add state on notification.
- Bump ui-services to 0.8.12.
Please, @pilhuhn, @mtho11 or @jshaughn review and merge if appropiate.
=> Generic comments on alerts

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
Minor PR to fix a style changed.
@pilhuhn can you merge it ?
Thanks
=> Fix style changed on Alert details

console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts, console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts
Show graphs for individual cpu(core)s.
=> Improvements to the platform display

console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts
Use stacking of metrics and also change bla.properties.name to bla.name usage
=> Further improvements to platform data

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, pom.xml
The triggers list portion of 654.
- Not yet forwarding to a details page.
=> Hawkular 654

console/src/main/scripts/bower.json
Also remove misleading patternfly resolution.
=> HAWKULAR-745 : Update angular-wizard so wz-disabled is supported

console/src/main/scripts/plugins/accounts/html/organization-accept-invitation.html, console/src/main/scripts/plugins/accounts/html/organization-memberships.html, console/src/main/scripts/plugins/accounts/html/organization-transfer-modal.html, console/src/main/scripts/plugins/accounts/html/organizations.html, console/src/main/scripts/plugins/accounts/html/user-settings.html, console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html, console/src/main/scripts/plugins/metrics/less/metrics.less
- Reducing width of container for Organization screens (too much space for too little content)
- Adequating transfer modal style of message
- Using same text style for error messages screens (organizations, user settings)
- Reverting Save/Cancel button to alert details screen
- More user friendly language for Enabled = true/false in triggers list
=> UI refinements from the demo

console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts
Minor fix for a bug found this morning during some local tests @pilhuhn, can you review and merge ? thx
=> HAWKULAR-748 Error on empty notes

console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/less/metrics.less
Make use of ng-animate instead.
=> Fix collapse/expand animation for Datasources

console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html, console/src/main/scripts/plugins/metrics/html/modals/alerts-ds-setup.html, console/src/main/scripts/plugins/metrics/html/modals/trigger-availability-setup.html, console/src/main/scripts/plugins/metrics/html/modals/trigger-range-percent-setup.html, console/src/main/scripts/plugins/metrics/html/modals/trigger-range-setup.html, console/src/main/scripts/plugins/metrics/html/modals/trigger-threshold-setup.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmAlerts.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebAlerts.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsAlerts.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/triggers/AvailabilityTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/RangeByPercentTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/RangeTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/ThresholdTrigger.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts
MikeT, please review.  This is the stuff I demoed to you for alerts center trigger detail views.  These views still need more work to be UX-compliant, but it should be a solid start.
=> Hawkular 654 2

dist/assembly.xml, dist/pom.xml, modules/hawkular-wildfly-agent-download/pom.xml, modules/hawkular-wildfly-agent-download/src/main/java/org/hawkular/component/wildflymonitor/WildFlyAgentServlet.java, modules/hawkular-wildfly-agent-download/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, modules/hawkular-wildfly-agent-download/src/main/webapp/WEB-INF/jboss-web.xml, modules/hawkular-wildfly-agent-download/src/main/webapp/WEB-INF/web.xml, pom.xml
provides a war that can be used by clients to download the agent module extension. The installer will use this also.
=> agent download war

console/src/main/scripts/gulpfile.js, console/src/main/scripts/package.json, console/src/main/scripts/plugins/accounts/ts/accountsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/directives/paginationDirectives.ts, console/src/main/scripts/plugins/topology/ts/d3Setup.ts
Add uglify and ng-annotate to plugins, enable minification in concat file. Add Injections in PersonaInterceptorService and to d3setup. Change controller to link in HkDataPagination and HkPagination.
=> Hawkular 500

console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html, console/src/main/scripts/plugins/metrics/html/url-availability.html, console/src/main/scripts/plugins/metrics/html/url-response-time.html, console/src/main/scripts/plugins/metrics/ts/metricsResponse.ts
Also fixed it in other places where this was/might happen.
Took the chance to also do some general improvements and respect line length in affected files.
=> HAWKULAR-518 : Fix tooltip cropped on "Update chart"

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html
Minor PR to fix a missing change
=> HAWKULAR-805 Action renames alert by event

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html, console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/html/directives/alert-info.html, console/src/main/scripts/plugins/metrics/html/directives/alert.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts
New directive alert-info for inserting alerts as one directive, insert this directive in JVM, Deployments, Web and Datasource. Thise files were styled as well so they corespond the new metrics.less file where some changes were made by Gabriel.
=> Hawkular 665

console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
Also added some additional type safety for ResourceId in the files that were touched.
=> HAWKULAR-414 Datasource wait time color is too light

console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-datasources-add.html, console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-datasources-driver-add.html, console/src/main/scripts/plugins/metrics/html/app-details/modals/detail-deployments-add.html
@cardosogabriel this one is for you.
=> Turn back on wizard step indicators.

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/html/directives/table-filters.html, console/src/main/scripts/plugins/metrics/ts/directives/filterDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/paginationDirectives.ts, console/src/main/scripts/plugins/metrics/ts/metricsAppServerList.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/serverStatus.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
Change version of angular-bootstrap and angular-patternfly so we can use newest version of simple filter from angular patternfly. Create new enums ServerStatus - for easy creation of server statuses. Server type - egain easy creation of server type for filtering. Create new directive, TableFilters for filtering over specific table. insert this directive to server list. Fix of NaN in Web alerts. Add search function to controller, which takes care of data. This way we can use searching in every table
=> HAWKULAR-127

console/src/main/scripts/plugins/directives/subtab/html/subtab.html
This is one that @khala found and fixed due to patternfly upgrade. I'm just committing his fix as he had to leave.
=> Fix broken date chooser.

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
XA Datasources are separated from non-XA Datasources,
requiring independent queries to inventory to retrieve them.
=> HAWKULAR-841 : Show XA Datasources in the DS tab

console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/html/directives/table-filters.html, console/src/main/webapp/index.html
There were changes to angular-ui bootstrap which caused the dropdowns to stop working.
The dropdown top-most element requires a "dropdown" directive, as class="dropdown"
is not sufficient.
=> HAWKULAR-843 : Fix dropdowns across console

console/src/main/scripts/plugins/accounts/less/accounts.less
add css rules so when user is logged out blur contents of screen.
=> HAWKULAR-775

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts, console/src/main/scripts/plugins/metrics/ts/services/alertRouterManager.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
Add alert router, which is responsible for registering functions when alerts are recieved from server. Register to this router Datasources, Deployments, JVM and Web. Remove unnnecessary inject field from these files and remove unused variables.
=> Alert Routering

console/src/main/scripts/plugins/directives/topbar/ts/topbarServices.ts, console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-jvm.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html, console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterDetails.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerJvmDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerWebDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/modals/appServerDatasourcesAddDialog.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsAppServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/metricsAppServerList.ts, console/src/main/scripts/plugins/metrics/ts/metricsGlobals.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/services/alertRouterManager.ts, console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts, pom.xml
Update inventory to 9.0.Final too.
=> Adapt UI to Agent and Metrics IDs change

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-details/app-server-details.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-overview.html, console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/html/directives/overview/common-tasks.html, console/src/main/scripts/plugins/metrics/html/directives/overview/donut-chart.html, console/src/main/scripts/plugins/metrics/html/directives/overview/label-editor.html, console/src/main/scripts/plugins/metrics/html/directives/overview/remove-label.html, console/src/main/scripts/plugins/metrics/html/directives/overview/server-details.html, console/src/main/scripts/plugins/metrics/html/directives/overview/spark-line-chart.html, console/src/main/scripts/plugins/metrics/html/directives/overview/status-overview.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerList.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/commonTasksDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/serverDetailsDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/statusOverviewDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts
add new page server overview. Add all alerts to this page, add graph about all alert in timeline, add graph about avarege JVM, add graph about connections to DB, add graph about web connections, add information about deployments. Show basic server information. Create labels inside overview panel. Labels can be added and removed. Fix graph with alerts, not it is much understandale and it show actual alerts in time. Fix NaN in web session alerts.
=> HAWKULAR-586

console/src/main/scripts/plugins/metrics/html/directives/alert-summary.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/triggers/availabilityTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/rangeByPercentTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/rangeTrigger.ts, console/src/main/scripts/plugins/metrics/ts/triggers/thresholdTrigger.ts, dist/src/main/resources/wildfly/patches/standalone.xsl, pom.xml
- Fix JVM  GC alerting by moving from ThresholdCondition to (new) RateCondition
- up to 0.7.0.Final of Alerts, which has the new RateCondition, and gets Hawkular off srcdep
- add newly required Infinispan caches for alerts, in standalone.xml
- Fix bug in 'Alert on Every Occurrence', this was not implented correctly and actually was not alerting on each occurrence
- Move bus to 0.7.3.Final (from srcdep) in preparation of Hawkular release
=> Hawkular 854

console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/html/url-list.html, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerList.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java, modules/pinger/src/main/java/org/hawkular/component/pinger/TraitsPublisher.java, pom.xml
Includes required update to Inventory 0.10.0.Final and API usage fixes to the Pinger
=> HAWKULAR-742 & HAWKULAR-743 : Handle switch persona at URL & App Servers

console/src/main/scripts/plugins/metrics/html/directives/url-list/item.html, console/src/main/scripts/plugins/metrics/html/directives/url-list/summary.html, console/src/main/scripts/plugins/metrics/html/partials/url-alerts-view.html, console/src/main/scripts/plugins/metrics/html/url-availability.html, console/src/main/scripts/plugins/metrics/html/url-list.html, console/src/main/scripts/plugins/metrics/html/url-response-time.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/appServerList.ts, console/src/main/scripts/plugins/metrics/ts/directives/url-list/urlItemController.ts, console/src/main/scripts/plugins/metrics/ts/directives/url-list/urlListDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts, console/src/main/scripts/plugins/metrics/ts/urlAvailabilityDetails.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts, console/src/main/scripts/plugins/metrics/ts/urlResponseTimeDetails.ts
change the URLs to be shown as tiles. Show sparkline graph at bottom of each tile. Style the URL detail with sidebar alerts. Change the view of filter, to be at same line.
=> HAWKULAR-815

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts
- also, change column header 'Resource Name' to 'Resource' to match Triggers list
=> Hawkular-888 linkify AlertCenter->Alerts->Resource

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, pom.xml
- improve inline documentation
- update alerts srcdep to version needed for fix
=> Hawkular-464 Fix regression in original feature work

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
Also fix an issue with ng-show/hide and fa-spin and re-enable debug info
=> HAWKULAR-519 : Show operation in progress spinner for deployment actions

console/src/main/scripts/plugins/metrics/html/alerts-center-list.html, console/src/main/scripts/plugins/metrics/html/alerts-center-triggers.html, console/src/main/scripts/plugins/metrics/ts/alertsCenterList.ts, console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts
Also fixes HAWKULAR-828 where the checkbox wasn't checked when clicking on the cell
=> HAWKULAR-896 : Respect the filter when selecting all alerts/triggers

console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts
Also enabled the option to prevent opening duplicates of last toastr
=> HAWKULAR-902 : Increase toastr timeout to 8 seconds

console/src/main/scripts/bower.json
This is required to have pfSelect directive working properly
=> HAWKULAR-906 : Move bootstrap-select dependendency up in bower.json

console/src/main/scripts/plugins/metrics/html/app-server-list.html, console/src/main/scripts/plugins/metrics/html/directives/overview/donut-chart.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/appServerList.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/serverDetailsDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/statusOverviewDirective.ts
Add percent number in donut graphs. Fix labels, so it is not needed to wait for refresh after inserting first label. Remove number of results in server list. Change message when no results are filtered. Fix wrong number of visible results, when filtering (filtering now on javascript not in HTML).
=> HAWKULAR-864

console/src/main/scripts/plugins/topology/less/priority01Topology.less, console/src/main/scripts/plugins/topology/ts/d3Setup.ts, console/src/main/scripts/plugins/topology/ts/topologyPlugin.ts
* fixing the ugly tooltips (css)
* fetching the a configuration for servers (feed id was HCoded for server nodes)
* fixing the links when double clicking on the items (the urls in the router were changed recently)
=> topology-view

console/src/main/scripts/plugins/metrics/ts/alertsCenterTriggerList.ts, pom.xml
- also, fix bug when enabling/disabling multiple triggers
=> Move to Alerts 0.8.1.Final

console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts, console/src/main/scripts/plugins/metrics/html/directives/url-list/item.html, console/src/main/scripts/plugins/metrics/html/directives/url-list/summary.html, console/src/main/scripts/plugins/metrics/html/url-list.html, console/src/main/scripts/plugins/metrics/ts/directives/url-list/urlItemController.ts, console/src/main/scripts/plugins/metrics/ts/directives/url-list/urlListDirective.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts
add datepicker which effects number of visible alerts in each tile in URL list. Add button to delete tile in URL list. Change directive scope to bindToController, this is better way of binding values to directive's controller.
=> HAWKULAR-889

console/src/main/scripts/d.ts/d3/d3.d.ts, console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts, console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/directives/datasources/detail.html, console/src/main/scripts/plugins/metrics/html/directives/overview/donut-chart.html, console/src/main/scripts/plugins/metrics/html/directives/url-list/item.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerList.ts, console/src/main/scripts/plugins/metrics/ts/directives/datasources/dataSourceController.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/statusOverviewDirective.ts, console/src/main/scripts/plugins/metrics/ts/eventNames.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertRouterManager.ts
create new screen with datasource detail. Add this screen to router, add breadcrumb back from this screen. Change datasource layout to tile list
=> HAWKULAR-796

console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/html/directives/alert-summary.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/AlertDefinitionTypes.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts
Beautify platform tab to look more like current style of application, add trigger builder.
HAWKULAR-792 Add Alert definitions to platform tab with available memory and CPU cores.
HAWKULAR-792 Remove unnecessary interfaces, they have been already defined.
HAWKULAR-792 fix calling promises, remove unnecessary code, change let to consts.
=> HAWKULAR-792

console/src/main/scripts/plugins/metrics/html/directives/overview/spark-line-chart.html, console/src/main/scripts/plugins/metrics/html/directives/overview/status-overview.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/urlList.ts
Align similar  style charts on same row and add x and y axes to the chart for better context.
=> Server overview reformat

console/src/main/scripts/plugins/directives/topbar/html/topbar.html, console/src/main/scripts/plugins/metrics/html/agent-installer.html, console/src/main/scripts/plugins/metrics/less/metrics.less
Not complete as design is not complete yet.
=> HAWKULAR-918 Reformat of screen to clean up a bit. Remove experimental status

console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts
Also fixes incorrect percentages shown in the pie hover
=> HAWKULAR-951 : Limit decimal places to 1 in DS Pie Chart.

console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/metrics/ts/directives/datasources/dataSourceController.ts
Also some misc fixes:
- Rename typo in method name getDatasource();
- Show the "»" after "All Application Servers" only when there's some entry after;
=> HAWKULAR-935 : Wait for $rootScope.currentPersona to exist @ DS Detail

dist/pom.xml, pom.xml
do not merge until agent 0.15.6.Final is released, which will be shortly.
=> HWKAGENT-50 - be able to configure the agent's feed ID when you start

console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts
Also corrects some text and labels in the FS Charts
=> HAWKULAR-964 : Fix toggling individual metrics in Platform FS Charts

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/accounts/html/token-qrcode-modal.html, console/src/main/scripts/plugins/accounts/html/tokens.html, console/src/main/scripts/plugins/accounts/ts/accountsGlobals.ts, console/src/main/scripts/plugins/accounts/ts/tokens.ts, console/src/main/webapp/index.html, pom.xml
- Tokens UI is now using cards
- Possibility to add a name/description to a token
- Possibility to set an expiration date
- Display QR Code for a token
=> HAWKULAR-949 - Refactored the Tokens UI.

console/src/main/scripts/gulpfile.babel.js, console/src/main/scripts/package.json, console/src/main/test/e2e/alert-center/alertCenter.e2e.spec.ts, console/src/main/test/e2e/alert-center/alertCenter.spec.ts, console/src/main/test/e2e/install-agent/installAgent.e2e.spec.ts, console/src/main/test/e2e/install-agent/installAgent.spec.ts, console/src/main/test/e2e/protractor.conf.js, console/src/main/test/e2e/servers/app-detail/datasources.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/datasources.spec.ts, console/src/main/test/e2e/servers/app-detail/deployments.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/deployments.spec.ts, console/src/main/test/e2e/servers/app-detail/jvm.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/jvm.spec.ts, console/src/main/test/e2e/servers/app-detail/overview.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/overview.spec.ts, console/src/main/test/e2e/servers/app-detail/platform.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/platform.spec.ts, console/src/main/test/e2e/servers/app-detail/transactions.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/transactions.spec.ts, console/src/main/test/e2e/servers/app-detail/web.e2e.spec.ts, console/src/main/test/e2e/servers/app-detail/web.spec.ts, console/src/main/test/e2e/servers/appList.e2e.spec.ts, console/src/main/test/e2e/servers/appList.spec.ts, console/src/main/test/e2e/topology/topology.e2e.spec.ts, console/src/main/test/e2e/topology/topology.spec.ts, console/src/main/test/e2e/url/urlList.e2e.spec.ts, console/src/main/test/e2e/url/urlList.spec.ts, console/src/main/test/e2e/utils/subTabUtil.ts
HAWKULAR-971 kick-off integration tests for UI. Click to server list, overview, URLs, alert center, topology, agent installer.
HAWKULAR-971 move test folder to same level as scripts. Add test cases for jvm, overview, datasources, platform, triggers, deployments, web - for now, justclicking on them and checking URL
=> HAWKULAR-971

console/src/main/scripts/plugins/metrics/html/partials/trigger-general-setup.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDatasourcesDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts
fix select in trigger setup. Also I have noticed that overview and datasources were not auto refreshed and had autorefresh commented out. So I turned auto refresh for these parts.
=> HAWKULAR-904

dist/src/main/resources/standalone.xsl
=> HAWKULAR-784 - Enable compression for serving the Hawkular UI from Undertow

console/src/main/scripts/plugins/accounts/html/tokens.html, console/src/main/scripts/plugins/accounts/less/accounts.less, console/src/main/scripts/plugins/metrics/less/metrics.less
Using flexbox. Looks good in Safari, Chrome and Firefox for Mac :)
=> Equal height in tokens cards

console/src/main/scripts/plugins/directives/topbar/html/topbar.html, console/src/main/scripts/plugins/metrics/html/directives/message-center.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/directives/messageCenterDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/statusOverviewDirective.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/errorsManager.ts, console/src/main/scripts/plugins/metrics/ts/services/notificationsService.ts
Add all toastr messages to this center. Create loading message, which is responsible for showing that something is happening on server. Add action message to message center, this message shows custom html which is for taking actions, either download button or redirect etc. Add show more button, add number of messages which were not yet read
HAWKULAR-960 fix registering of watchers and listeners.
Watcher for experimental mode was added all the time to , this might lead to some memory problems. Also JDR export success and error were reigstered in same way.
=> HAWKULAR-960 Create message center.

modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailDataMessage.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/AvailPublisher.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/Availability.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/Log.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/MetricReceiver.java, modules/avail-creator/src/main/java/org/hawkular/component/availcreator/SingleAvail.java, modules/avail-creator/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, modules/avail-creator/src/main/webapp/WEB-INF/jboss-web.xml, modules/avail-creator/src/main/webapp/WEB-INF/web.xml, modules/end-to-end-test/src/test/java/org/hawkular/integration/test/AbstractTestBase.java, modules/end-to-end-test/src/test/java/org/hawkular/integration/test/Scenario1ITest.java, modules/pinger/src/main/java/org/hawkular/component/pinger/Log.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricDataMessage.java, modules/pinger/src/main/java/org/hawkular/component/pinger/MetricPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingDestination.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingManager.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingStatus.java, modules/pinger/src/main/java/org/hawkular/component/pinger/PingerConfiguration.java, modules/pinger/src/main/java/org/hawkular/component/pinger/Traits.java, modules/pinger/src/main/java/org/hawkular/component/pinger/TraitsPublisher.java, modules/pinger/src/main/java/org/hawkular/component/pinger/UrlChangesCollector.java, modules/pinger/src/main/webapp/WEB-INF/jboss-all.xml, modules/pinger/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, modules/pinger/src/main/webapp/WEB-INF/jboss-web.xml, modules/pinger/src/main/webapp/WEB-INF/web.xml, modules/pinger/src/test/java/org/hawkular/component/pinger/PingerTestUtils.java
_400 should be 200' is not very helpful_ - (https://travis-ci.org/hawkular/hawkular/builds/107327309#L2328)
=> more informative itests failures 

console/src/main/scripts/plugins/metrics/ts/AlertDefinitionTypes.ts, console/src/main/scripts/plugins/metrics/ts/appServerDetails.ts, console/src/main/scripts/plugins/metrics/ts/metricsTypes.ts, console/src/main/scripts/plugins/metrics/ts/services/alertsManager.ts, console/src/main/scripts/plugins/metrics/ts/urlList.ts
New API for actions is array of objects, so correspond with them. Create new builder for this. For now don't store properties in since no properties are available in constructor of new action in trigger
=> HAWKULAR-1027 change creating of action in trigger based on new API

modules/avail-creator/pom.xml, modules/avail-creator/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, modules/end-to-end-test/pom.xml, modules/hawkular-api-parent/hawkular-rest-api/pom.xml, modules/hawkular-api-parent/hawkular-rest-api/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, modules/hawkular-api-parent/hawkular-rx/pom.xml, modules/hawkular-api-parent/pom.xml, modules/pinger/pom.xml, modules/pinger/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, pom.xml
I think I'd need the following people to provide input (testing to see if things are not broken, seeing if anything else can be removed, ...):
@ppalaga , @Jiri-Kremser , @pilhuhn 
If there's someone else who needs to review/test this, feel free to mention :)
=> HAWKULAR-1020 - Cleaned and optimized some dependencies for modules.

modules/hawkular-api-parent/hawkular-listener/src/main/java/org/hawkular/listener/bus/CommandEventListener.java, pom.xml
- bump to final version
- add CommandEvenListener to hawkular-listeners jar
=> Hawkular Alerts 1.0.0.Final, HWKALERTS-133

modules/hawkular-api-parent/hawkular-listener/src/main/java/org/hawkular/listener/bus/InventoryEventListener.java
- handle the fact that the actual URL is not supplied in
the resource create event published by inventory.
=> HAWKULAR-1040 Issue with URL trigger definition

modules/hawkular-api-parent/hawkular-listener/src/main/java/org/hawkular/listener/bus/InventoryEventListener.java
=> HAWKULAR-1040 use actual URL now that we have it

console/src/main/scripts/plugins/metrics/html/alerts-center-detail.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-datasources.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/html/partials/trigger-general-setup.html, console/src/main/scripts/plugins/metrics/less/metrics.less
=> Hawkular 1022

console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts, pom.xml
This reverts commit d00892faecb50c3404ce582d6da37e0881ef9513.
=> Revert "HAWKULAR-1038 : Fix for platform CPU stacked chart"

console/src/main/scripts/bower.json, console/src/main/scripts/d.ts/angular/angular.d.ts, console/src/main/scripts/plugins/directives/subtab/html/subtab.html, console/src/main/scripts/plugins/directives/subtab/ts/subtabDirective.ts, console/src/main/scripts/plugins/directives/topbar/html/topbar.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/radio-filter.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/side-filter-container.html, console/src/main/scripts/plugins/metrics/html/explorer.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/app-details/appServerDeploymentsDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts, console/src/main/scripts/plugins/metrics/ts/app-details/appServerPlatformDetails.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/alertSetupNotificationDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/explorer/sideFilterContainerDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/hkComponents.ts, console/src/main/scripts/plugins/metrics/ts/directives/navTree.ts, console/src/main/scripts/plugins/metrics/ts/directives/paginationDirectives.ts, console/src/main/scripts/plugins/metrics/ts/directives/validFileDirective.ts, console/src/main/scripts/plugins/metrics/ts/explorer.ts, console/src/main/scripts/plugins/metrics/ts/metricsPlugin.ts, console/src/main/scripts/plugins/metrics/ts/services/alertRouterManager.ts, console/src/main/scripts/plugins/metrics/ts/services/metricsService.ts, console/src/main/scripts/plugins/metrics/ts/urlAvailabilityDetails.ts, console/src/main/scripts/plugins/metrics/ts/viewController.ts, console/src/main/scripts/plugins/topology/directives/hawkularTopologyGraph.ts, console/src/main/scripts/plugins/topology/directives/hawkularTopologyIcon.ts, console/src/main/scripts/plugins/topology/ts/topologyPlugin.ts, console/src/main/webapp/index.html
Add tree of child resources after selecting one resource
HAWKULAR-1037 change tree to be patternfly tree
Also new components and directives for side panel which is for filtering metrics
Remove wrong dependency from metricsPlugin
=> HAWKULAR-1037 Fix selecting of resources and their metrics

console/src/main/scripts/plugins/metrics/html/directives/overview/status-overview.html, console/src/main/scripts/plugins/metrics/ts/app-details/appServerOverviewDetails.ts, console/src/main/scripts/plugins/metrics/ts/directives/overview/statusOverviewDirective.ts, console/src/main/scripts/plugins/metrics/ts/inventoryExplorer.ts
if selected range of time is in yesterday/today, show this in overview page, if the date is older than yesterday show actual date. In inventory explorer automatically update time under timepicker when refreshed (either manualy or automatically).
=> HAWKULAR-1049 change to date on overview page to show today/yesterday

console/src/main/scripts/plugins/metrics/html/directives/explorer/radio-filter.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/resource-tree.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/side-filter-container.html, console/src/main/scripts/plugins/metrics/html/explorer.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/directives/explorer/resourceTreeDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/explorer/sideFilterContainerDirective.ts, console/src/main/scripts/plugins/metrics/ts/directives/navTree.ts, console/src/main/scripts/plugins/metrics/ts/inventoryExplorer.ts, console/src/main/scripts/plugins/metrics/ts/viewController.ts
Move resource selector and feed selector to the center of page. Move resource tree to it's own component
Remove funcion, we use ES6 coding
=> HAWKULAR-1037 update UI to be more aligned

console/src/main/scripts/plugins/directives/topbar/html/topbar.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/radio-filter.html, console/src/main/scripts/plugins/metrics/html/directives/explorer/side-filter-container.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/metrics/ts/directives/explorer/sideFilterContainerDirective.ts
Resource, feed and metric can be now collapsed with clicking on header
Make graph selector hidden by default
=> HAWKULAR-1054 collapse option for graph selector

console/src/main/scripts/plugins/metrics/html/directives/alert-summary.html
=> If no tag matches, just emit some default message.

console/src/main/scripts/bower.json, console/src/main/scripts/plugins/accounts/less/accounts.less, console/src/main/scripts/plugins/directives/subtab/less/subtab.less, console/src/main/scripts/plugins/directives/topbar/less/topbar.less, console/src/main/scripts/plugins/metrics/html/app-details/detail-deployments.html, console/src/main/scripts/plugins/metrics/html/directives/table-filters.html, console/src/main/scripts/plugins/metrics/less/metrics.less, console/src/main/scripts/plugins/topology/less/priority01Topology.less, console/src/main/webapp/index.html
Includes update to patternfly 3.3.1 angular-patternfly 3.3.1 with some
needed fixes
=> HAWKULAR-1006 : Update to Patternfly 3.3.1

console/src/main/scripts/plugins/metrics/html/app-details/detail-platform.html, console/src/main/scripts/plugins/metrics/html/app-details/detail-web.html, console/src/main/scripts/plugins/metrics/html/directives/datasources/detail.html, console/src/main/scripts/plugins/metrics/html/explorer.html, console/src/main/scripts/plugins/metrics/html/url-response-time.html
@mtho11 could you pleser review? Yesterday we missed to remove some height properties.
=> Charts removed height property
